### ISSUE TITLE
[BUG] Devcontainer fails to open when repository is cloned on Windows

### ISSUE THREAD

**Issue by ooeygui** [Azure-Samples/graphrag-accelerator#101]
**Describe the bug**
When cloning this repository on Windows using Git on Windows instead of Git Bash, you'll encounter build errors related to line endings being corrupted in Bash scripts. This prevents the dev container from starting.

**Expected behavior**
The Devcontainer should start without issues even when the repository is cloned on Windows.

**Desktop (please complete the following information):**
 - OS: Windows 11

> NOTE: I'm fixing this issue in https://github.com/ooeygui/graphrag-accelerator, by updating https://github.com/ooeygui/graphrag-accelerator/blob/main/.gitattributes to force line endings on bash scripts, and binary downloads on other files

**Additional context**
This was mentioned in https://github.com/Azure-Samples/graphrag-accelerator/issues/56.

**Comment by jgbradley1** [comment]
Closing this issue for now as we think [this](https://github.com/Azure-Samples/graphrag-accelerator/pull/102) PR solved the problem.
