### ISSUE TITLE
Unable to connect to apim end point /manpage/openai.json

### ISSUE THREAD

**Issue by Haritha-Maturi** [Azure-Samples/graphrag-accelerator#108]
While trying to hit this manpage/openai.json it's getting 503 error.

![apim_error](https://github.com/user-attachments/assets/287b24ee-1c23-4c46-b5b9-b073743bec56)

**To Reproduce**
1. Give all the required parameters
2. Run deploy.sh script

Checking for GraphRAG external IP Available.
Registering GraphRAG API with APIM...
Checking for GraphRAG availability.................... Failed.

**Expected behavior**
The endpoint should return an json file.

**Comment by pwine123** [comment]
Facing the same issue. Following.

**Comment by rnpramasamyai** [comment]
Please check whether pods are crashing in AKS and review the pod logs.

**Comment by timothymeyers** [comment]
Is anyone still facing this issue? @Haritha-Maturi  @pwine123  ?

Please check your AKS pod logs as @rnpramasamyai mentioned and report back.

**Comment by pwine123** [comment]
@timothymeyers - please review findings in bug #120

**Comment by Haritha-Maturi** [comment]
As per @rnpramasamyai mentioned the issue is with pods once I make them work the issue is resolved. Thank you
