### ISSUE TITLE
[BUG]Checking for GraphRAG availability.................... Failed:  error

### ISSUE THREAD

**Issue by pwine123** [Azure-Samples/graphrag-accelerator#120]
**Describe the bug**
During deployment, i get the error: Checking for GraphRAG availability.................... Failed.

**To Reproduce**
I looked at the aks pod logs: graphrag-query and graphrag-index had warnings with the following message "NotTriggerScaleUp: pod didn't trigger scale-up: 1 node(s) didn't match Pod's node affinity/selector, 1 Insufficient cpu"

"FailedScheduling: 0/2 nodes are available: 1 Insufficient cpu, 1 node(s) didn't match Pod's node affinity/selector. preemption: 0/2 nodes are available: 1 No preemption victims found for incoming pod, 1 Preemption is not helpful for scheduling.."
![image](https://github.com/user-attachments/assets/67d26c1a-63a5-4555-9283-9d23d7d63b68)

FYI - due to the deployment error i encountered, i had to update aks.bicep to use "standard_d4s_v3" in line 33 and line 41.
![image](https://github.com/user-attachments/assets/895b03f8-d621-457a-9e2f-6d487796350d)

Not sure if this is causing the insufficient cpu error. I tried by updating the max node counts to higher number in aks.bicep file but continue to run into the same insufficient cpu error.

**Expected behavior**
Expecting deployment to succeed.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by rnpramasamyai** [comment]
@pwine123
You are experiencing an insufficient CPU issue. Please request an increase in CPU resources.

**Comment by pwine123** [comment]
After moving graph rag node pool to e16as VM sku, the deployment worked. Thanks @timothymeyers  and @rnpramasamyai
