### ISSUE TITLE
when deploying some values are not getting from GRAPHRAG_API_BASE 

### ISSUE THREAD

**Issue by jamil77944** [Azure-Samples/graphrag-accelerator#130]
Hi Below is the error I receive when I try with github actions:
<img width="527" alt="image" src="https://github.com/user-attachments/assets/50ca76c9-d61b-4012-99ac-e450a377a6e2">
Looks like GRAPHRAG_API_BASE and possibly other values are not storing in the variable.

Please let me know if I am missing any steps.

**Comment by timothymeyers** [comment]
@jamil77944 are you calling your deploy script like `./deploy.sh -p main.parameters.json`  (or `bash deploy.sh -p main.parameters.json`) from the `/infra` directory? Is that parameter file stored in the `/infra` directory?

Could you share a snip of your main.parameters.json file (sanitized)?

Can you share more of the deploy.sh run output that happens before that error?

**Comment by jamil77944** [comment]
<img width="632" alt="image" src="https://github.com/user-attachments/assets/813684a0-f872-430d-9638-646b1f9a1aa7">

Is this the right approach?

**Comment by jamil77944** [comment]
i have set that up in main.parameters.json

**Comment by timothymeyers** [comment]
@jamil77944  in a previous comment you mentioned `main.parameters.json` but I see that you are using `deploy.parameters.json` - confirm you're using the right file please.

In your action runner step, I see you setting the account but I don't see a step to log into Azure. Is that happening in a previous job or step somewhere?

**Comment by cynthiajiangatl** [comment]
Need to add resource group for AOAI service to avoid deployment errors.

For existing Azure OpenAI service, it may not be in the newly created resource group, needs to add AOAI_RESOURCE_GROUP in deploy.parameters.json and update the deploy.sh in a couple of places.

requiredParams=(
    LOCATION
    GRAPHRAG_API_BASE
    GRAPHRAG_API_VERSION
    GRAPHRAG_LLM_MODEL
    GRAPHRAG_LLM_DEPLOYMENT_NAME
    GRAPHRAG_EMBEDDING_MODEL
    GRAPHRAG_EMBEDDING_DEPLOYMENT_NAME
    RESOURCE_GROUP
    **AOAI_RESOURCE_GROUP**
)

deployAzureResources () {
    echo "Deploying Azure resources..."
    local SSH_PUBLICKEY=$(jq -r .publicKey <<< $SSHKEY_DETAILS)
    exitIfValueEmpty "$SSH_PUBLICKEY" "Unable to read ssh publickey, exiting..."
    local aoaiName=$(az cognitiveservices account list **-g $AOAI_RESOURCE_GROUP** --query "[?contains(properties.endpoint, '$GRAPHRAG_API_BASE')] | [0].name" -o tsv)
    exitIfValueEmpty "$aoaiName" "Unable to retrieve AOAI name from GRAPHRAG_API_BASE, exiting..."

assignAOAIRoleToManagedIdentity() {
    printf "Assigning 'Cognitive Services OpenAI Contributor' role to managed identity... "
    local servicePrincipalId=$(jq -r .azure_workload_identity_principal_id.value <<< $AZURE_OUTPUTS)
    exitIfValueEmpty "$servicePrincipalId" "Unable to parse service principal id from azure outputs, exiting..."
    local scope=$(az cognitiveservices account list **-g $AOAI_RESOURCE_GROUP** --query "[?contains(properties.endpoint, '$GRAPHRAG_API_BASE')] | [0].id" -o tsv)
    az role assignment create --only-show-errors \
        --role "Cognitive Services OpenAI Contributor" \
        --assignee "$servicePrincipalId" \
        --scope "$scope" > /dev/null 2>&1
    exitIfCommandFailed $? "Error assigning role to service principal, exiting..."
    printf "Done.\n"
}

**Comment by jamil77944** [comment]
@timothymeyers sorry it is deploy.parameters.json.

![image](https://github.com/user-attachments/assets/58479f6b-4959-4162-93bb-fe095a04d890)
I have modified the step also to include bash. But I get the same error running through github actions. Do you believe it is because I am logging in with a service principal? the service principal has the owner level in the resource group

**Comment by timothymeyers** [comment]
No it looks like your GRAPHRAG_API_BASE is not set properly or there is no deployment of Azure Open AI in your subscription corresponding with the GRAPHRAG_API_BASE you've provided. 

What is it set to in deploy.parameters.json? It should look like `"https://<Azure-Open-AI-Resource>.openai.azure.com/"`

[This is the line](https://github.com/Azure-Samples/graphrag-accelerator/blob/43191446828d065325e8d07670980067b726e982/infra/deploy.sh#L296) causing the error. It is essentially querying your subscription to verify that the instance of Azure Open AI exists and returning the name of that resource. So, either the name is incorrect, or the resource does not exist in your subscription.

**Comment by jamil77944** [comment]
![Screenshot 2024-08-09 110323](https://github.com/user-attachments/assets/57b7fd54-512c-4ecb-8103-1a633ff9b72d)
This is how I set in deploy.parameters.json

**Comment by jgbradley1** [comment]
@jamil77944 Are you able to try this deployment in `eastus2` instead of `East US`? I've heard some users are having trouble deploying in `eastus` even when quota appears to be fine and we're still investigating the issue. I think it could be an issue specific to the `eastus` region.

**Comment by jamil77944** [comment]
I see. Thank you so much. I was able to deploy locally inside eastus region. I could not do it with github actions. I will try it with eastus2
