### ISSUE TITLE
Assigning 'Cognitive Services OpenAI Contributor' role to managed identity.. brings an error

### ISSUE THREAD

**Issue by jamil77944** [Azure-Samples/graphrag-accelerator#131]
Deployment name: graphrag-deploy-2024-08-08_16-47-58
WARNING: The configuration value of bicep.use_binary_from_path has been set to 'false'.
ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Resources/deployments/graphrag-deploy-2024-08-08_16-47-58","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/xxxxx/resourceGroups/xxxxx/providers/Microsoft.Resources/deployments/aks","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/xxxxxx/resourceGroups/xxxxx/providers/Microsoft.Resources/deployments/aks","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/xxxxx/resourceGroups/xxxxx/providers/Microsoft.ContainerService/managedClusters/aks-emt-grapghrag-dev-15/agentPools/graphrag","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"OverconstrainedAllocationRequest","message":"Code=\"OverconstrainedAllocationRequest\" Message=\"Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:\\n  - Networking Constraints (such as Accelerated Networking or IPv6)\\n  - VM Size\\n\" Target=\"0\"","details":[{"code":"OverconstrainedAllocationRequest","target":"0","message":"Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:\n  - Networking Constraints (such as Accelerated Networking or IPv6)\n  - VM Size\n"}]}]}]}]},{"code":"ResourceDeploymentFailure","target":"/subscriptions/xxxxx/resourceGroups/xxxxx/providers/Microsoft.Resources/deployments/apim","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"DeploymentFailed","target":"/subscriptions/xxxxxx/resourceGroups/xxxxx/providers/Microsoft.Resources/deployments/apim","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"Timeout","message":"Call to Management API apim-emt-grapghrag-dev-15.management.azure-api.net:3443 timed out for the Developer SKU service which will have inherent capacity issues due to it's scale. Please refer to SLA at https://aka.ms/apimsla and considering upgrading to a SKU Tier with higher SLA."}]}]}]}}
**Assigning 'Cognitive Services OpenAI Contributor' role to managed identity...  ________________________________**
/  Uh oh, an error has occurred. \
\  Please see message below.     /
 ‾‾‾‾‾‾‾‾‾‾/‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
          /
      __ /
     /  \
    ~    ~
   / \  /_\
   \o/  \o/
    |    |
    ||   |/
    ||   ||
    ||   ||
    | \_/ |
    \     /
     \___/

Unable to parse service principal id from azure outputs, exiting...

This happens when the deployment runs locally.

**Comment by timothymeyers** [comment]
This error appears to be related to a lack of resource capacity in your subscription quota and/or the region you're deploying to. I'd suggest you go to the **Azure Portal** -> **{your resource group}** -> **Deployments** and look for failed deployments. Try digging into the error messages to see which resource deployment is failing and why.

**Comment by jamil77944** [comment]
this is solved. thanks

**Comment by yzlee** [comment]
> this is solved. thanks

how did you solve it? I am facing same problem

**Comment by SridharArrabelly** [comment]
@jamil77944 Could you explain how this issue was resolved? I'm encountering the same problem. All resources have been deployed successfully, but it seems the problem arises when attempting to add role assignments. appreciated.
