### ISSUE TITLE
Stop using one-click azure deploy - over $1300 bill

### ISSUE THREAD

**Issue by chinyeefan** [Azure-Samples/graphrag-accelerator#137]
I followed the recommended Azure configuration as in [here](https://github.com/Azure-Samples/graphrag-accelerator/blob/main/docs/DEPLOYMENT-GUIDE.md), and forget about it until one month later and I see my bill is
 **!!!!!!!!!! OVER $1300!!!!!!!!!!!!**
![Screenshot 2024-08-12 at 12 07 37 PM](https://github.com/user-attachments/assets/7b379c44-32eb-4c55-8102-f117ed84a7c8)

If the whole accelerator can be done in a laptop, I don't see any reason why it needs a `E16as v5` instance in Azure. This is absolutely an overqualified expensive option for running this project. Here's what a `E16as v5` looks like 
![Screenshot 2024-08-12 at 12 10 08 PM](https://github.com/user-attachments/assets/b6b53b0b-1c1b-419d-a250-3dffffcf441c)
 

I am deeply concerned it's a sneaky tactic to sell Azure services. This kind of behaviour is not only unethical but also severely damages the trust users place in open source projects.

I expect immediate action to address this issue, including inform people of the costs and adjust the service to a reasonable tier

**Comment by jeffwilcox** [comment]
Hey @chinyeefan, could you open an Azure Support ticket within the portal about the billing from this sample experience? Hopefully they can help understand the situation and they may be able to waive the costs if this is the first time it's been an issue for your account.

Appreciate you taking the time to open the issue, I think we can work with teams to emphasize the warnings even more for similar projects that could have a large compute cost if run for too long.

Thanks,
Jeff
Microsoft open source office
