### ISSUE TITLE
[BUG] terminate called after throwing an instance of 'PAL_SEHException' on Mac silicon chip M1 M2

### ISSUE THREAD

**Issue by yzlee** [Azure-Samples/graphrag-accelerator#161]
**Describe the bug**

If you are using mac silicon and vscode dev container. You will meet these error: 
```
ERROR: rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2

Assigning 'Cognitive Services OpenAI Contributor' role to managed identity... ________________________________
/ Uh oh, an error has occurred.
\ Please see message below. /
```
and
```
Deployment name: graphrag-deploy-2024-08-31_23-19-14
ERROR: terminate called after throwing an instance of 'PAL_SEHException'
Assigning 'Cognitive Services OpenAI Contributor' role to managed identity...  ________________________________
/  Uh oh, an error has occurred. \
\  Please see message below.     /
 ‾‾‾‾‾‾‾‾‾‾/‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
          /
      __ /
     /  \
    ~    ~
   / \  /_\
   \o/  \o/
    |    |
    ||   |/
    ||   ||
    ||   ||
    | \_/ |
    \     /
     \___/

Unable to parse service principal id from azure outputs, exiting...
graphrag-solution-accelerator-py3.10
```

It's not your fault. what you need do is just modify Dockerfile:
1. change the first line to ` FROM --platform=linux/amd64 python:3.10 `
2. add the second line `ENV DOTNET_EnableWriteXorExecute=0`

below is the principle explaination:
https://stackoverflow.com/questions/77105077/how-to-run-docker-in-devcontainers-on-mac-m1-apple-silicon
https://stackoverflow.com/questions/78578636/how-to-get-dotnet-8-azure-function-to-run-on-an-m3-chip-inside-a-docker-containe

**To Reproduce**
i am the owner of the resource group.
I am the owner of subscription.
Everything is set following https://github.com/Azure-Samples/graphrag-accelerator/blob/main/docs/DEPLOYMENT-GUIDE.md
I am using macbook M2.

**Expected behavior**
echo is misleading

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 14.6.1
 - M2 chip

**Comment by yzlee** [comment]
This log may help:

+ local aoaiName=graphraggpt
+ exitIfValueEmpty graphraggpt 'Unable to retrieve AOAI name from GRAPHRAG_API_BASE, exiting...'
+ local value=graphraggpt
+ local 'msg=Unable to retrieve AOAI name from GRAPHRAG_API_BASE, exiting...'
+ '[' -z graphraggpt ']'
+ [[ graphraggpt == \n\u\l\l ]]

**Comment by yzlee** [comment]
This log may also help:
graphrag-solution-accelerator-py3.10vscode@docker-desktop:/graphrag-accelerator/infra$ az cognitiveservices account list
[
  {
    "etag": "\"01039724-0000-0100-0000-66d3a1740000\"",
    "id": "/subscriptions/8a12b9b3-b59b-4d6d-b7bd-177662209022/resourceGroups/graphragtest/providers/Microsoft.CognitiveServices/accounts/graphraggpt",
    "identity": null,
    "kind": "OpenAI",
    "location": "eastus",
    "name": "graphraggpt",
    "properties": {
      "abusePenalty": null,
      "allowedFqdnList": null,
      "apiProperties": null,
      "callRateLimit": {
        "count": null,
        "renewalPeriod": null,
        "rules": [
          {
            "count": 30.0,
            "dynamicThrottlingEnabled": null,
            "key": "openai.dalle.post",
            "matchPatterns": [
              {
                "method": "POST",
                "path": "dalle/*"
              },
              {
                "method": "POST",
                "path": "openai/images/*"
              }
            ],
            "minCount": null,
            "renewalPeriod": 1.0
          },
          {
            "count": 30.0,
            "dynamicThrottlingEnabled": null,
            "key": "openai.dalle.other",
            "matchPatterns": [
              {
                "method": "*",
                "path": "dalle/*"
              },
              {
                "method": "*",
                "path": "openai/operations/images/*"
              }
            ],
            "minCount": null,
            "renewalPeriod": 1.0
          },
          {
            "count": 100.0,
            "dynamicThrottlingEnabled": null,
            "key": "openai.assistants.default",
            "matchPatterns": [
              {
                "method": "*",
                "path": "openai/assistants/*"
              },
              {
                "method": "*",
                "path": "openai/threads/*"
              },
              {
                "method": "*",
                "path": "openai/vector_stores/*"
              }
            ],
            "minCount": null,
            "renewalPeriod": 1.0
          },
          {
            "count": 30.0,
            "dynamicThrottlingEnabled": null,
            "key": "openai",
            "matchPatterns": [
              {
                "method": "*",
                "path": "openai/*"
              }
            ],
            "minCount": null,
            "renewalPeriod": 1.0
          },
          {
            "count": 30.0,
            "dynamicThrottlingEnabled": null,
            "key": "default",
            "matchPatterns": [
              {
                "method": "*",
                "path": "*"
              }
            ],
            "minCount": null,
            "renewalPeriod": 1.0
          }
        ]
      },
      "capabilities": [
        {
          "name": "VirtualNetworks",
          "value": null
        },
        {
          "name": "CustomerManagedKey",
          "value": null
        },
        {
          "name": "MaxFineTuneCount",
          "value": "100"
        },
        {
          "name": "MaxRunningFineTuneCount",
          "value": "1"
        },
        {
          "name": "MaxUserFileCount",
          "value": "50"
        },
        {
          "name": "MaxTrainingFileSize",
          "value": "512000000"
        },
        {
          "name": "MaxUserFileImportDurationInHours",
          "value": "1"
        },
        {
          "name": "MaxFineTuneJobDurationInHours",
          "value": "720"
        },
        {
          "name": "MaxEvaluationRunDurationInHours",
          "value": "5"
        },
        {
          "name": "MaxRunningEvaluationCount",
          "value": "2"
        },
        {
          "name": "TrustedServices",
          "value": "Microsoft.CognitiveServices,Microsoft.MachineLearningServices,Microsoft.Search"
        },
        {
          "name": "RaiMonitor",
          "value": null
        }
      ],
      "commitmentPlanAssociations": null,
      "customSubDomainName": "graphraggpt",
      "dateCreated": "2024-08-31T23:01:31.0807755Z",
      "deletionDate": null,
      "disableLocalAuth": null,
      "dynamicThrottlingEnabled": null,
      "encryption": null,
      "endpoint": "https://graphraggpt.openai.azure.com/",
      "endpoints": {
        "OpenAI Dall-E API": "https://graphraggpt.openai.azure.com/",
        "OpenAI Language Model Instance API": "https://graphraggpt.openai.azure.com/",
        "OpenAI Model Scaleset API": "https://graphraggpt.openai.azure.com/",
        "OpenAI Whisper API": "https://graphraggpt.openai.azure.com/"
      },
      "internalId": "bb081f6a3d784aea9d9a4297d910ebc0",
      "isMigrated": false,
      "locations": null,
      "migrationToken": null,
      "networkAcls": null,
      "privateEndpointConnections": [],
      "provisioningState": "Succeeded",
      "publicNetworkAccess": "Enabled",
      "quotaLimit": null,
      "restore": null,
      "restrictOutboundNetworkAccess": null,
      "scheduledPurgeDate": null,
      "skuChangeInfo": null,
      "userOwnedStorage": null
    },
    "resourceGroup": "graphragtest",
    "sku": {
      "capacity": null,
      "family": null,
      "name": "S0",
      "size": null,
      "tier": null
    },
    "systemData": {
      "createdAt": "2024-08-31T23:01:30.325731+00:00",
      "createdBy": "lawrence@nikshepmaknoorhirect.onmicrosoft.com",
      "createdByType": "User",
      "lastModifiedAt": "2024-08-31T23:01:30.325731+00:00",
      "lastModifiedBy": "lawrence@nikshepmaknoorhirect.onmicrosoft.com",
      "lastModifiedByType": "User"
    },
    "tags": {},
    "type": "Microsoft.CognitiveServices/accounts"
  }
]

**Comment by yzlee** [comment]
deploy.parameters.json

{
  "GRAPHRAG_API_BASE": "https://graphraggpt.openai.azure.com/",
  "GRAPHRAG_API_VERSION": "2023-03-15-preview",
  "GRAPHRAG_EMBEDDING_DEPLOYMENT_NAME": "text-embedding-ada-002",
  "GRAPHRAG_EMBEDDING_MODEL": "text-embedding-ada-002",
  "GRAPHRAG_LLM_DEPLOYMENT_NAME": "gpt-4o",
  "GRAPHRAG_LLM_MODEL": "gpt-4o",
  "LOCATION": "eastus",
  "RESOURCE_GROUP": "graphragtest"
}

**Comment by gmpark-factagora** [comment]
I had the same problem and the proposed solution worked. Thank you for the information!

**Comment by vlad-tsoy** [comment]
This has also worked for me. This TIP should be added to the FAQ IMHO. Thank you!
