### ISSUE TITLE
[BUG] Tenant ID, application ID, principal ID, and scope are not allowed to be updated. (Code: RoleAssignmentUpdateNotPermitted)

### ISSUE THREAD

**Issue by MarkHmnv** [Azure-Samples/graphrag-accelerator#168]
**Describe the bug**
At the point of Azure Kubernetes creation, or, more specifically, at running "Microsoft.Authorization/roleAssignments", the following error occurs: "Tenant ID, application ID, principal ID, and scope are not allowed to be updated. (Code: RoleAssignmentUpdateNotPermitted)"

**To Reproduce**
1. Go to 'infra'
2. Run the 'deploy.sh'
3. See error

**Desktop:**
 - Windows 11

**Additional context**
I have set all the roles as specified in the README for the deployment

**Comment by akirakak** [comment]
@MarkHmnv 
I am experiecing the same error. Have you resolved this? If so, how did you resolve it?

**Comment by puneetpawaia** [comment]
I got this error as well. Any solution? I am running the deployment from WSL2 under Windows 11. And I am using the lastest code as of today.

**Comment by puneetpawaia** [comment]
@MarkHmnv ,and @akirakak did you manage to resolve this? Would appreciate if you could share how you resolved it?
