### ISSUE TITLE
[FEATURE] Update README.md file to have kubelogin as a pre-req.  Had to install manually in ubuntu 22.04 

### ISSUE THREAD

**Issue by caddyjoe77** [Azure-Samples/graphrag-accelerator#198]
Update README.md file to have kubelogin as a pre-req.  Had to install manually in ubuntu 22.04 

glad to update if needed.  Something I had to manually do.

**Comment by kiyoung-on-ms** [comment]
I got the same one in Ubuntu 22.04 as well.
Please update the deployment guide.

https://github.com/Azure-Samples/graphrag-accelerator/blob/main/docs/DEPLOYMENT-GUIDE.md

**Comment by caddyjoe77** [comment]
thank you!! Excellent work by the team
