### ISSUE TITLE
[BUG] Internal Server Error in Local Query

### ISSUE THREAD

**Issue by james-tn** [Azure-Samples/graphrag-accelerator#41]
Whenever I ran query/local, this error occurred:

Internal Server Error
b'Unexpected internal server error'
CPU times: user 6.76 ms, sys: 3.43 ms, total: 10.2 ms
Wall time: 2.21 s
<Response [500]>
**To Reproduce**
# perform a local query
local_response = local_search(
    index_name=index_name, query="How to reset my password?"
)

parse_query_response(local_response, return_context_data=True)
**Expected behavior**
Local query should return the result

**Comment by toma3233** [comment]
I am getting the same error when running a local query. 

![image](https://github.com/user-attachments/assets/bcae321f-7acd-4a38-b4be-99b86fd8e3e4)

I double checked my indexing operation and it is complete. I am also using the latest version of graphrag-accelerator.
