### ISSUE TITLE
Give estimates of minimal costs to run the accelerator

### ISSUE THREAD

**Issue by fire** [Azure-Samples/graphrag-accelerator#44]
**Is your feature request related to a problem? Please describe.**
I want to run the accelerator but I don't know how much it'll cost.

**Describe the solution you'd like**
Give estimates of minimal costs to run the accelerator.

**Describe alternatives you've considered**
Try to find other instructions how to test.

**Additional context**
graphrag is a cool idea.

**Comment by zhanpengjie** [comment]
if possible deploy with docker local?

**Comment by fire** [comment]
I was able to run via python on windows 11 and 2 Nvidia RTX 3090s.

On my project's manual it takes around 2 hours for indexing.
