### ISSUE TITLE
[BUG] Indexing Job Fails ( more details below )

### ISSUE THREAD

**Issue by maulik-soni-tfs** [Azure-Samples/graphrag-accelerator#48]
**Describe the bug**
Running Quickstart.ipynb - Start new indexing job

```
<Response [200]>
{
    'status_code': 200,
    'index_name': 'test_graph_rag3',
    'storage_name': 'test_graph_rag3',
    'status': 'failed',
    'percent_complete': 12.5,
    'progress': "Workflow 'create_final_covariates' started.",
}
```

**Expected behavior**
Indexing should be 100% complete

**Comment by eyast** [comment]
When an indexing job fails, I find many logs and artefacts on the blob storage that I configured during the installation. I browse to blob_containers\{index_name}\reports and find a JSON file that includes the steps that were taken, as well as any errors reported back. You can access this blob interactively using Azure Storage Explorer if you've deployed the solution with the `-g` switch.

**Comment by jgbradley1** [comment]
I recently pushed a PR through that renamed the `reports` directory to `logs`. I also hooked up the logging to app insights so that it is easier to debug any failed API calls.

**Comment by timothymeyers** [comment]
@maulik-soni-tfs are you still having an issue? Also, if you've not seen the thread here, definitely check it out.

https://github.com/Azure-Samples/graphrag-accelerator/issues/55#issuecomment-2212369690

**Comment by timothymeyers** [comment]
Closing as stale
