### ISSUE TITLE
Deployment Failure - The template deployment 'aks' is not valid

### ISSUE THREAD

**Issue by gerglitzen** [Azure-Samples/graphrag-accelerator#64]
I followed the deployment guide step by step. 
- I created a new RG `graphrag` at `East US 2`. 
- I deployed the required AzureOpenAI models
- add the required Azure Role Base Access

I'm using Linux Mint 21.3

I have an error while running the deployment
```bash
bash deploy.sh -p deploy.parameters.json
```

The error message is:
```json
{
    "status":"Failed",
    "error":{
        "code":"DeploymentFailed",
        "target":"/subscriptions/xxxxxx/resourceGroups/graphrag/providers/Microsoft.Resources/deployments/graphrag-deploy-2024-07-08_09-59-44",
         "message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
        "details":[{
            "code":"InvalidTemplateDeployment",
            "message":"The template deployment 'aks' is not valid according to the validation procedure. The tracking id is 'xxxx'. See inner errors for details.",
            "details":[{
                "code":"InternalOperationError",
                "message":"Preflight validation check for resource(s) for container service aks-g6jrqeyika2zs in resource group graphrag failed. Message: We are unable to serve this request due to an internal error, Correlation ID: xxx, Operation ID: xxx, Timestamp: 2024-07-08T08:00:23Z.. Details: "
}]}]}}
```

**Comment by timothymeyers** [comment]
@gerglitzen Verify that the AKS SKUs in the accelerator are available in `East US 2` and that you have quota. 

In some of my tests, I ran into issues in various regions where I had to downgrade from `standard_d4s_v5` to `standard_d4s_v3`
https://github.com/Azure-Samples/graphrag-accelerator/blob/497aa5e176c422c958b850e8d65a4d11df3d665e/infra/core/aks/aks.bicep#L33

**Comment by Arvoid00** [comment]
@timothymeyers Hi!

Setting the VM size to 'standard_d4s_v3' worked. Thanks!
However I am getting the following error: 

```
Creating a free tier cluster is unavailable at this time in region westeurope. 
To create a new cluster, we recommend using an alternate region, or create a paid tier cluster.
```

I am unsure which parameters to change to make it a standard tier cluster, or how to check which VM types are compatible for the application and in which regions the free tier exist. Where do I find this info? 

A simple copilot chat (in Azure) returned that all VMs are available for free tier in all regions, which is not true, given the error above...

**Comment by timothymeyers** [comment]
Hey @Arvoid00 glad to hear that helped you on to the next step.

Someone else had this same 'free tier' availability issue in `westeurope` - check out this discussion for some guidance on configuring for standard (or I'd just try a different region) - https://github.com/Azure-Samples/graphrag-accelerator/discussions/72

**Comment by Arvoid00** [comment]
Thanks for guiding to those docs. Must help for sure.
Currently creating a bunch of resource groups in different regions in hope of one actually deploying due to high demand issues (for cosmos too actually).

**Comment by gerglitzen** [comment]
@timothymeyers At the end I moved my deployment to another region (swedencentral) and I changed the aks.bicep file to `standard_d4s_v3` and it worked for me too!
