### ISSUE TITLE
[BUG/QUESTION] Error connecting to APIM endpoints

### ISSUE THREAD

**Issue by Arvoid00** [Azure-Samples/graphrag-accelerator#80]
**Describe the bug**
Hello there, I cannot reach APIM endpoints. The development portal is online.

`https://<redacted>.azure-api.net/manpage/openai.json`
returns:
```
{ "statusCode": 404, "message": "Resource not found" }
```

`https://<redacted>.management.azure-api.net/`
returns:
```
{"error":{"code":"MissingOrIncorrectVersionParameter","message":"API version query parameter is not specified or was specified incorrectly.  Supported versions: 2014-02-14-preview,2014-02-14,2015-09-15,2016-07-07,2016-10-10,2017-03-01,2018-01-01,2018-06-01-preview,2019-01-01,2019-12-01-preview,2019-12-01,2020-06-01-preview,2020-12-01,2021-01-01-preview,2021-04-01-preview,2021-08-01,2021-12-01-preview,2022-04-01-preview,2022-08-01,2022-09-01-preview,2023-03-01-preview,2023-05-01-preview,2023-09-01-preview  Example query param format: api-version=SupportedVersion","details":null}}
```

**To Reproduce**
1. setup following params:
```
{
  "GRAPHRAG_API_BASE": "https://graphrag-azure-openai.openai.azure.com/",
  "GRAPHRAG_API_VERSION": "2023-09-01-preview",
  "GRAPHRAG_EMBEDDING_DEPLOYMENT_NAME": "Embeddings",
  "GRAPHRAG_EMBEDDING_MODEL": "text-embedding-3-large",
  "GRAPHRAG_LLM_DEPLOYMENT_NAME": "GraphRag-Azure-OpenAI",
  "GRAPHRAG_LLM_MODEL": "GPT-4o",
  "LOCATION": "francecentral",
  "RESOURCE_GROUP": "GraphRAG-north-europe"
}
```
_other optional params are not provided._

2. run deploy script

`bash deploy.sh -p deploy.parameters.json`

Error while deploying in `waitForGraphrag()` function:
```
+ az rest --method get --url https://<redacted>.azure-api.net/manpage/openapi.json
+ '[' 1 -eq 0 ']'
+ sleep 40
+ printf .
.+ (( i++ ))
+ (( i < 40 ))
+ '[' false == true ']'
+ printf ' Failed.\n'
 Failed.
+ exit 1
```

**Expected behavior**
The endpoints should be available, but I do not know why they are not.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker Devcontainer
 - Version: Python 3.12

**Additional context**
-

**Comment by timothymeyers** [comment]
I've not encountered this in my testing but will keep an eye out and try to reproduce. Thanks for bringing to our attention @Arvoid00

**Comment by jgbradley1** [comment]
@Arvoid00 in some organizations, you may have an Azure Policy in place that applies additional NSG rules on top of APIM at deployment time. In my experience, this is what impacts the `deploy.sh` script running to final completion, specifically at the rest call that you reference. If your organization has a VPN, ensure you are connected to it before running the `deploy.sh` script.

**Comment by rnpramasamyai** [comment]
@Arvoid00
Please update your GRAPHRAG_API_VERSION to use 2024-02-15-preview instead of 2023-09-01-preview.

**Comment by timothymeyers** [comment]
any luck @Arvoid00?

**Comment by Arvoid00** [comment]
Hi all, thanks for the responses. I have not been able to test said proposals due to a shift in priorities. I will provide an update when I can. For now this issue can be closed.

**Comment by jamiexfonesbdo** [comment]
Did you manage to fix this? @Arvoid00  I tried changing the Graph_API_Version in the params and still get the same issue as you. If I navigate to the APIM Gateway URL directly (without swagger link) I get a 404 error. When I add the swagger link I get a 503 error.
