### ISSUE TITLE
What capacity is required for OpenAI Models?

### ISSUE THREAD

**Issue by jaypaddy** [Azure-Samples/graphrag-accelerator#86]
**Describe the bug**
I deployed the Solution Accelerator. I was able to submit an Indexing job. However i get the following WARNING...

WARNING:graphrag.llm.base.rate_limiting_llm:Process failed to invoke LLM 1/10 attempts. Cause: rate limit exceeded, will retry. Recommended sleep for 0 seconds. Follow recommendation? True

Im using the wikiarticles indexing quickstart. 

What is required in terms of capacity for OpenAI?
My capacity is as follows"
![image](https://github.com/user-attachments/assets/0ed25739-c3a8-419f-bc46-0f3753503e99)

**Comment by jliberta** [comment]
@jaypaddy https://github.com/Azure-Samples/graphrag-accelerator/blob/main/docs/DEPLOYMENT-GUIDE.md#1-deploy-azure-openai-service

**Comment by jaypaddy** [comment]
There is similar issue as this... looks like the tokens_per_minute: 80000 has to be increased in Azure OpenAI or decrease it in the config file.
