### ISSUE TITLE
[QUESTION] Visualize .graphml file

### ISSUE THREAD

**Issue by gerglitzen** [Azure-Samples/graphrag-accelerator#95]
Can you suggest a good way how to open and visualize the `.graphml` file interactively? Something like in the graphrag demo was presented would be nice. Can be a desktop app or a python package in a jupyter notebook too.

I('m using Linux Mint 21.3)

**Comment by timothymeyers** [comment]
Check out this thread @gerglitzen 

https://github.com/microsoft/graphrag/issues/418
